# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Set the RNG Seed from within Rcpp
#' 
#' Within Rcpp, one can set the R session seed without triggering
#' the CRAN rng modifier check. 
#' @param seed A \code{unsigned int} that is the seed one wishes to use. 
#' @return A set RNG scope.
#' @examples
#' set.seed(10)
#' x = rnorm(5,0,1)
#' set_seed(10)
#' y = rnorm(5,0,1)
#' all.equal(x,y, check.attributes = F)
NULL

dnorm_cpp <- function(x, mean, sd) {
    .Call('Darts_dnorm_cpp', PACKAGE = 'Darts', x, mean, sd)
}

rdarts_post_pr_cpp <- function(par, data, tau, sigma, is_paired = FALSE, inc_eff_len = 2.0, skp_eff_len = 1.0) {
    .Call('Darts_rdarts_post_pr_cpp', PACKAGE = 'Darts', par, data, tau, sigma, is_paired, inc_eff_len, skp_eff_len)
}

rdarts_posterior_MCMC_sampler <- function(N, tau, sigma, data, init_val, proposal_width = 0.01, burnin = 1000L, thinning = 5L, random_state = 1L, is_paired = FALSE, inc_eff_len = 2.0, skp_eff_len = 1.0) {
    .Call('Darts_rdarts_posterior_MCMC_sampler', PACKAGE = 'Darts', N, tau, sigma, data, init_val, proposal_width, burnin, thinning, random_state, is_paired, inc_eff_len, skp_eff_len)
}

darts_likelihood_cpp <- function(mu, delta, data, loglik, inc_eff_len = 2.0, skp_eff_len = 1.0) {
    .Call('Darts_darts_likelihood_cpp', PACKAGE = 'Darts', mu, delta, data, loglik, inc_eff_len, skp_eff_len)
}

set_seed <- function(seed) {
    invisible(.Call('Darts_set_seed', PACKAGE = 'Darts', seed))
}

darts_posterior_MCMC_sampler <- function(N, tau, data, init_val, proposal_width = 0.05, burnin = 1000L, thinning = 1L, random_state = 1L, inc_eff_len = 2.0, skp_eff_len = 1.0) {
    .Call('Darts_darts_posterior_MCMC_sampler', PACKAGE = 'Darts', N, tau, data, init_val, proposal_width, burnin, thinning, random_state, inc_eff_len, skp_eff_len)
}

